version: "3.8"

services:
  order:
    restart: always
    build:
      context: order
      args:
        NODEJS_DOCKER_IMAGE: ${NODEJS_DOCKER_IMAGE}
    volumes:
      - ./order:/app
      - /app/node_modules
    ports:
      - 3000:3000
    command: [yarn, start:debug]

  inventory:
    build:
      context: inventory
      args:
        NODEJS_DOCKER_IMAGE: ${NODEJS_DOCKER_IMAGE}
    restart: always
    volumes:
      - ./inventory:/app
      - /app/node_modules
    ports:
      - 3001:3001
    command: [yarn, start:debug]

  payment:
    build:
      context: payment
      args:
        NODEJS_DOCKER_IMAGE: ${NODEJS_DOCKER_IMAGE}
    restart: always
    volumes:
      - ./payment:/app
      - /app/node_modules
    ports:
      - 3002:3002
    command: [yarn, start:debug]

  broker:
    image: bitnami/kafka:3.3.1
    volumes:
      - kafka_data:/var/lib/kafka/data
    user: root
    ports:
      - 9092:9092
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_BROKER_ID=1
      - KAFKA_KRAFT_CLUSTER_ID=LelM2dIFQkiUFvXCEcqRWA
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@broker:9093
      - ALLOW_PLAINTEXT_LISTENER=yes

volumes:
  kafka_data:
